version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: devPass
      MYSQL_DATABASE: devDB
      MYSQL_USER: devUser
      MYSQL_PASSWORD: devPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
